### PR TITLE
Update for 6.1

### LINKED ISSUE #12: CharacterSync doesn't work with 6.1 update
Plugin is outdated after the Dalamud 6.1 update.

### PR DESCRIPTION
**Pull request by ZyphiraZircon**
Quick fix? This should fix the "out of date" message and allow people to use it again.

fixes #12

### CODE REVIEW

**Comment by Werns** [comment]
This did not fix the outdated message.

**Comment by AetherCollective** [comment]
Workaround:

Edit the `%AppData%\XIVLauncher\installedPlugins\Dalamud.CharacterSync\2.0.0.4\Dalamud.CharacterSync.json` file and set `DalamudApiLevel` from `5` to `6`.

I have no idea how to get this into a pull request. Can someone more knowledgeable find how this value is being created/set and update it?

**Comment by DorkmasterFlek** [comment]
I can't actually find `DalamudApiLevel` anywhere in the code.  I'm guessing this is some kind of config file generated by Dalamud itself when the plugin is installed?  If that's the case, I don't know why other plugins updated fine however.

**Comment by AetherCollective** [comment]
Yea that's the issue I ran into yesterday when I tried :/

**Comment by AetherCollective** [comment]
Where is Dalamud downloading the release from?

Edit: I found where it is downloading the release from, but it is missing from the repo now. Maybe it needs to be recreated?

**Pull request merged**
