### PR TITLE
Update to .net 6.0, version bump.

### PR DESCRIPTION
**Pull request by reckhou**

### CODE REVIEW

**Comment by Ammako** [comment]
DalamudApiLevel is auto-generated at build time, for what it's worth.

**Review by conklib — APPROVED** [review]

**Comment by reckhou** [comment]
@Ammako doesn't seem to be the case, after updating Dalamud Packager to the newest version the DalamudApiLevel isn't being generated. Maybe there's something missing in the original settings?

**Comment by Ammako** [comment]
Strange, when I made the changes to dalamudpackager version on my end and built, it got auto-generated.

Exact same changes as yours, except that I didn't manually add api level in the json (it put it there automatically for me.)

**Comment by VengefulRacoon** [comment]
is this getting updated anytime soon?

**Comment by DorkmasterFlek** [comment]
Can this get updated at least to a testing build so we can get it via that option in Dalamud?

**Comment by Ammako** [comment]
Visual Studio Community 2022: https://visualstudio.microsoft.com/downloads/

Pick .net desktop development workload, add Git for Windows under individual components

When it asks what to do at first launch, pick Clone a repository. Under repository location, paste `https://github.com/reckhou/Dalamud.CharacterSync.git`

* If it doesn't automatically open the solution, do it manually under File --> Open --> Project/Solution

Set the Debug dropdown to Release, then Build --> Build Solution just above

Your build should be at `C:\Users\<user>\source\repos\Dalamud.CharacterSync\Dalamud.CharacterSync\bin\Release\Dalamud.CharacterSync\latest.zip`

Extract that into a folder under installedPlugins in your xivlauncher folder, or replace your existing files

Alternatively: if you already have the latest (testing?) build, simply changing DalamudApiLevel to 7 in the json should be enough. A rebuild to .net 6.0 using newer dalamud packager version doesnt seem to be required, yet.

**Comment by DorkmasterFlek** [comment]
I do have the latest testing build.  Updating the API level in the JSON config file did fix it for now, thanks!

**Review by goaaats — APPROVED** [review]

**Pull request merged**
