### PR TITLE
give this to someone that crashes.

### PR DESCRIPTION
**Pull request by daemitus**

### CODE REVIEW

**Comment by daemitus** [comment]
theres a really noisy print right at the start of the hook. maybe we'll see something interesting.

**Comment by daemitus** [comment]
If we end up going this way, its probably worth adding  some checks if path > 260, switch to a \\?\ longpath, blah blah.

**Comment by daemitus** [comment]
Disregard old comments.  lets see what breaks.

**Comment by goaaats** [comment]
Thank you very much

**Pull request merged**
